import React,{createContext,useCallback,useContext,useMemo,useState}from"react";import type{ViewModel}from"@/utils/adapter";import{factIndicesForNode,nodeLabel}from"@/utils/adapter";
interface Selection{plantPart?:string;use?:string;nodeId?:string;factIndex?:number}
interface State{vm:ViewModel;selection:Selection;selectPlantPart:(v?:string)=>void;selectUse:(v?:string)=>void;selectNode:(v?:string)=>void;selectFact:(v?:number)=>void;clearSelection:()=>void;scrollTo:(id:string)=>void;highlightedNodeIds:Set<string>;highlightedFactIndices:Set<number>}
const C=createContext<State|null>(null);
export function ExplorationProvider({vm,children}:{vm:ViewModel;children:React.ReactNode}){const[selection,setSelection]=useState<Selection>({});
 const selectPlantPart=useCallback((v?:string)=>setSelection(s=>({plantPart:s.plantPart===v?undefined:v,use:s.use,nodeId:undefined,factIndex:undefined})),[]);const selectUse=useCallback((v?:string)=>setSelection(s=>({plantPart:s.plantPart,use:s.use===v?undefined:v,nodeId:undefined,factIndex:undefined})),[]);const selectNode=useCallback((v?:string)=>setSelection(s=>({plantPart:undefined,use:undefined,nodeId:s.nodeId===v?undefined:v,factIndex:undefined})),[]);const selectFact=useCallback((v?:number)=>setSelection(s=>({...s,factIndex:v})),[]);const clearSelection=useCallback(()=>setSelection({}),[]);
 const scrollTo=useCallback((id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})},[]);
 const highlightedNodeIds=useMemo(()=>{const ids=new Set<string>();if(selection.plantPart){const p=vm.parts.find(x=>x.name===selection.plantPart);p?.nodeIds.forEach(id=>ids.add(id));p?.uses.flatMap(u=>u.nodeIds).forEach(id=>ids.add(id));vm.evidenceFacts.filter(f=>f.entities?.plant_part===selection.plantPart).flatMap(f=>f.nodeIds).forEach(id=>ids.add(id));}
 if(selection.use){vm.parts.flatMap(p=>p.uses).filter(u=>u.name===selection.use).flatMap(u=>u.nodeIds).forEach(id=>ids.add(id));vm.evidenceFacts.filter(f=>(f.entities?.therapeutic_use??f.entities?.use)===selection.use).flatMap(f=>f.nodeIds).forEach(id=>ids.add(id));}
 if(selection.nodeId){ids.add(selection.nodeId);vm.graph.relationships.filter(r=>r.source===selection.nodeId||r.target===selection.nodeId).forEach(r=>{ids.add(r.source);ids.add(r.target)});}
 return ids},[selection,vm]);
 const highlightedFactIndices=useMemo(()=>{const idxs=new Set<number>();if(selection.plantPart)vm.evidenceFacts.forEach((f,i)=>{if(f.entities?.plant_part===selection.plantPart)idxs.add(i)});if(selection.use)vm.evidenceFacts.forEach((f,i)=>{if((f.entities?.therapeutic_use??f.entities?.use)===selection.use)idxs.add(i)});if(selection.nodeId)factIndicesForNode(vm,selection.nodeId).forEach(i=>idxs.add(i));if(selection.factIndex!=null)idxs.add(selection.factIndex);return idxs},[selection,vm]);
 return <C.Provider value={{vm,selection,selectPlantPart,selectUse,selectNode,selectFact,clearSelection,scrollTo,highlightedNodeIds,highlightedFactIndices}}>{children}</C.Provider>}
export function useExploration(){const c=useContext(C);if(!c)throw new Error("useExploration must be used within ExplorationProvider");return c}
