export type AnyRecord=Record<string,any>;
export interface NodeVM{id:string; type:string; labels:string[]; properties:AnyRecord}
export interface RelVM{id:string; type:string; source:string; target:string; properties:AnyRecord}
export interface GraphVM{intent:string; cypher:string; params:AnyRecord; rowCount:number; nodes:NodeVM[]; relationships:RelVM[]; rows:AnyRecord[]}
export interface FactVM{index:number; rowIndex:number; entities:AnyRecord; measurements:AnyRecord[]; nodeIds:string[]; relationshipIds:string[]}
export interface PartVM{name:string; factCount:number; uniqueUseCount:number; nodeIds:string[]; factIndices:number[]; uses:{name:string;nodeIds:string[];factIndices:number[]}[]; representativeUses:string[]; explanation?:string}
export interface ViewModel{raw:AnyRecord; query:string; intent:string; subject:string|null; subjectProfile:AnyRecord|null; answer:AnyRecord|null; statistics:AnyRecord; graph:GraphVM; evidenceFacts:FactVM[]; parts:PartVM[]; interaction:AnyRecord; notes:string[]}
const normType=(s:string)=>String(s||"").replace(/[^a-zA-Z0-9]/g,"").toLowerCase();
function nodeType(n:any){const labels=n.labels||[]; const l=labels[0]||n.type||"Unknown"; return l.replace(/\s+/g,"");}
function factEntities(f:any){return f?.entities||{};}
export function buildViewModel(raw:AnyRecord):ViewModel{
 const graphRaw=raw?.graph||{}; const graph:GraphVM={intent:graphRaw.intent||raw?.intent||"unknown",cypher:graphRaw.cypher||"",params:graphRaw.params||{},rowCount:Number(graphRaw.row_count??0),nodes:(graphRaw.nodes||[]).map((n:any)=>({id:String(n.id),type:nodeType(n),labels:n.labels||[],properties:n.properties||{}})),relationships:(graphRaw.relationships||[]).map((r:any)=>({id:String(r.id),type:String(r.type||""),source:String(r.source),target:String(r.target),properties:r.properties||{}})),rows:graphRaw.rows||[]};
 const eFacts=(raw?.evidence?.facts||[]).map((f:any,i:number)=>({index:i,rowIndex:Number(f.row_index??i),entities:factEntities(f),measurements:f.measurements||[],nodeIds:(f.provenance?.node_ids||f.path?.nodes||[]).map((x:any)=>typeof x==='string'?x:String(x.id)),relationshipIds:(f.provenance?.relationship_ids||f.path?.relationships||[]).map((x:any)=>typeof x==='string'?x:String(x.id))}));
 const fr=raw?.frontend||{}; const subjectRaw=fr.subject; const subjectProfile=(subjectRaw&&typeof subjectRaw==="object")?subjectRaw:null; const subject=typeof subjectRaw==="string"?subjectRaw:subjectProfile?.scientific_name||subjectProfile?.name||raw?.entities?.find((e:any)=>e.entity_type==="plant")?.canonical_value||raw?.entities?.find((e:any)=>e.entity_type==="phytochemical")?.canonical_value||null;
 const parts=(fr.plant_parts||[]).map((p:any)=>{const name=p.plant_part??p.name; if(name==null||String(name).trim()==="") return null; return {name:String(name),factCount:Number(p.fact_count??0),uniqueUseCount:Number(p.unique_use_count??0),nodeIds:(p.node_ids||[]).map(String),factIndices:(p.fact_indices||[]).map(Number),uses:(p.uses||[]).filter((u:any)=>u&&u.name!=null&&String(u.name).trim()!=="").map((u:any)=>({name:String(u.name),nodeIds:(u.node_ids||[]).map(String),factIndices:(u.fact_indices||[]).map(Number)})),representativeUses:(p.representative_uses||[]).filter((x:any)=>x!=null&&String(x).trim()!=="").map(String),explanation:p.explanation};}).filter(Boolean) as PartVM[];
 return {raw,query:raw?.query||"",intent:raw?.intent||graph.intent,subject:String(subject||"")||null,subjectProfile,answer:raw?.answer?.answer||raw?.answer||null,statistics:raw?.frontend?.statistics||raw?.answer?.statistics||raw?.evidence?.summary||{},graph,evidenceFacts:eFacts,parts,interaction:fr.interaction||{},notes:raw?.notes||[]};
}
export function nodeLabel(n:NodeVM){const v=n.properties?.name??n.properties?.scientific_name??n.properties?.inchi_key??n.properties?.bioactivity_id??n.properties?.target_chembl_id??n.properties?.mesh_id??n.id;return typeof v==="string"||typeof v==="number"?String(v):JSON.stringify(v);}
export function entityNodeIds(vm:ViewModel, name:string){return vm.graph.nodes.filter(n=>nodeLabel(n)===name).map(n=>n.id)}
export function factIndicesForNode(vm:ViewModel,id:string){return vm.evidenceFacts.filter(f=>f.nodeIds.includes(id)).map(f=>f.index)}
